import type { CollectionConfig } from "payload";

/**
 * Uploaded images (property photos, covers). `upload: true` turns this into a
 * media library. Sizes are generated by sharp on upload; in production the
 * files live in Vercel Blob (wired via the storage adapter in payload.config).
 */
export const Media: CollectionConfig = {
  slug: "media",
  access: {
    // Public read so the marketing site can render images; writes require login.
    read: () => true,
  },
  upload: {
    mimeTypes: ["image/*"],
    imageSizes: [
      { name: "thumbnail", width: 400, height: 300, position: "centre" },
      { name: "card", width: 768, height: 576, position: "centre" },
      { name: "hero", width: 1600, height: 1000, position: "centre" },
    ],
    focalPoint: true,
  },
  fields: [
    {
      name: "alt",
      type: "text",
      localized: true,
      label: { en: "Alt text", ru: "Alt-текст" },
      admin: { description: "Short image description for accessibility/SEO." },
    },
  ],
};
